# -*- coding: utf-8 -*-
"""Network Analysis and Community Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKYgrwW1BbCxeOcU-7lO2w31ebT7-_yO
"""

---

## Project 7: Network Analysis and Community Detection

---

### `network_analysis_community.py`

```python
import networkx as nx
import matplotlib.pyplot as plt
from networkx.algorithms import community

def main():
    G = nx.karate_club_graph()

    communities_generator = community.greedy_modularity_communities(G)
    communities = [list(c) for c in communities_generator]

    colors = ['r', 'b', 'g', 'y', 'm']
    color_map = {}
    for i, community_nodes in enumerate(communities):
        for node in community_nodes:
            color_map[node] = colors[i % len(colors)]

    node_colors = [color_map[node] for node in G.nodes()]

    nx.draw(G, node_color=node_colors, with_labels=True, node_size=300)
    plt.title("Karate Club Community Detection")
    plt.show()

if __name__ == "__main__":
    main()